spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-mydatabase}
    username: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-mypassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    cache-names: usedTokens
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=24h
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: moataz.noaman12@gmail.com
    password: wyxjzyli ketiewuv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/emails/
    suffix: .html
    mode: HTML
    cache: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
project:
  location: location/
base:
  url: "localhost:8080/"
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    api-docs:
      path: /api-docs
computer:
  cpu: CORE_I7
  ram: 16RAM
  gpu: NVIDIA_RTX3050