package com.moataz.examPlatform.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ExamAttemptDto {
    private UUID examId;
    private UUID studentId;
    private String examTitle;
    private String examType;
    private Integer marks;
    private String status; // e.g., "completed", "in-progress", "not-started"
    private String startTime; // ISO 8601 format
    private String endTime; // ISO 8601 format
    private Integer score;
    private String duration;

    // Getters and Setters can be generated by Lombok or manually added
}
